"""Bootstrap adapter for the committed canonical-story reference.

This adapter only maps reference files into a temporary project and delegates
lifecycle state to public provenance APIs. It does not fabricate accepted
metadata sidecars or alter the committed example.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

import yaml

from auteur.blueprint import StoryBlueprint
from auteur.identity import StoryIdentity
from auteur.provenance import ArtifactStore
from auteur.expression.pilot import ExpressionStore
from auteur.expression.composition import ChapterExpressionStore
from auteur.expression.book import BookExpressionStore


class CanonicalStoryBootstrap:
    def __init__(self, reference_root: Path) -> None:
        self.reference_root = Path(reference_root)

    def copy_to(self, workspace: Path) -> Path:
        """Copy the canonical reference tree into an isolated dogfood workspace.

        ``workspace`` must be completely outside ``self.reference_root``.
        Dogfood workspaces are throwaway project roots regenerated by tests
        and scripts to exercise the full narrative pipeline end-to-end; if a
        workspace is ever created *inside* the committed reference tree (e.g.
        ``examples/canonical_story/temp_something/``), a later bootstrap run
        against that same reference tree will recursively copy the workspace
        back into itself, producing nested duplicate artifacts with
        conflicting artifact IDs (``source Scene Realization is invalid``).

        This method fails explicitly instead of allowing that recursion.
        Future dogfood projects should pick a workspace path outside any tree
        that is itself a bootstrap source -- e.g. a `tempfile.TemporaryDirectory`
        (see ``scripts/dogfood-canonical-story.py``) or a dedicated,
        gitignored directory such as ``temp/dogfood/<project>/`` at the
        repository root (see ``tests/test_book_external_routing_dogfood.py``)
        -- and let this method validate the choice rather than hand-rolling
        the copy.

        Re-running ``copy_to`` against the same workspace is safe: any
        previous ``canonical_story/`` copy is removed first, so repeated
        bootstrap is deterministic.
        """
        workspace_path = Path(workspace)
        resolved_workspace = workspace_path.resolve()
        resolved_reference = self.reference_root.resolve()

        if self._is_within(resolved_workspace, resolved_reference):
            raise ValueError(
                f"Dogfood workspace {resolved_workspace} is inside the canonical "
                f"reference tree {resolved_reference}; bootstrapping would "
                "recursively copy the reference tree into itself. Choose a "
                "workspace path outside the reference tree (e.g. "
                "temp/dogfood/<project>/ at the repository root)."
            )
        if self._is_within(resolved_reference, resolved_workspace):
            raise ValueError(
                f"Canonical reference tree {resolved_reference} is inside the "
                f"requested workspace {resolved_workspace}; refusing to copy "
                "to avoid infinite recursion."
            )

        destination = workspace_path / "canonical_story"
        if destination.exists():
            shutil.rmtree(destination)
        shutil.copytree(self.reference_root, destination)
        return destination

    @staticmethod
    def _is_within(path: Path, ancestor: Path) -> bool:
        """Return True if ``path`` is ``ancestor`` itself or nested inside it."""
        return path == ancestor or ancestor in path.parents

    def accept_scene_realizations(self, project_root: Path, *, accepted_by: str = "canonical-dogfood") -> list[dict[str, Any]]:
        """Map and accept the five realization documents through ArtifactStore."""
        store = ArtifactStore(project_root)
        accepted = []
        for index, source in enumerate(sorted(Path(project_root).glob("canonical_story/chapter_01/scene_*/realization.yaml")), 1):
            path = Path(project_root) / "chapters" / "01" / "scenes" / f"scene_01_{index:02d}.yaml"
            path.parent.mkdir(parents=True, exist_ok=True)
            data = yaml.safe_load(source.read_text(encoding="utf-8")) or {}
            data.update({"id": f"scene_01_{index:02d}", "chapter_id": "chapter_01", "order": index})
            path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")
            metadata = store.accept(path, "scene_realization", accepted_by=accepted_by,
                                    rationale="canonical demonstration project bootstrap")
            if metadata is not None:
                accepted.append(metadata.model_dump(mode="json"))
        return accepted

    def accept_native_identity_and_structure(self, project_root: Path, *, accepted_by: str = "canonical-dogfood") -> dict[str, Any]:
        """Create native temporary Identity/Blueprint/Chapter artifacts and accept them."""
        root = Path(project_root)
        store = ArtifactStore(root)
        identity = StoryIdentity.model_validate({
            "title": "The Lantern at Low Water",
            "core_answer": "Mercy can preserve responsibility without erasing harm.",
            "target_experience": {"primary": "dread", "progression": "unease -> dread -> release", "avoid": ["triumphal revenge"]},
            "story_type": {"medium": "novel", "mode": "tragic", "genre": "grimdark_fantasy", "length_class": "short_story"},
            "central_engine": {"want": "Protect the river town", "resistance": "The magistrate's boat is endangered", "conflict": "Mercy versus remembered harm", "stakes": "Mara's moral identity and the town's survival", "change": "Mara chooses responsibility without forgiveness"},
        })
        identity_path = root / "story_identity.yaml"
        identity.to_yaml(identity_path)
        identity_meta = store.accept(identity_path, "story_identity", accepted_by=accepted_by, rationale="canonical reference identity")

        sample = Path(__file__).parents[2] / "examples" / "sample_blueprint.yaml"
        blueprint = StoryBlueprint.from_yaml(sample)
        blueprint_path = root / "blueprint.yaml"
        blueprint_path.write_text(yaml.safe_dump(blueprint.model_dump(mode="json"), sort_keys=False), encoding="utf-8")
        blueprint_meta = store.accept(blueprint_path, "blueprint", accepted_by=accepted_by, rationale="native blueprint adapter; human-readable blueprint retained")

        chapter_path = root / "chapters" / "01" / "outline.yaml"
        chapter_path.parent.mkdir(parents=True, exist_ok=True)
        chapter_path.write_text(yaml.safe_dump({"chapter_id": "chapter_01", "chapter_number": 1, "blueprint_id": blueprint_meta.artifact_id if blueprint_meta else "blueprint", "scenes": [f"scene_01_{i:02d}" for i in range(1, 6)]}, sort_keys=False), encoding="utf-8")
        chapter_meta = store.accept(chapter_path, "chapter_outline", accepted_by=accepted_by, rationale="canonical five-scene structure")
        return {"identity": identity_meta.model_dump(mode="json") if identity_meta else None, "blueprint": blueprint_meta.model_dump(mode="json") if blueprint_meta else None, "chapter": chapter_meta.model_dump(mode="json") if chapter_meta else None}

    def bootstrap_expressions(self, project_root: Path, *, accepted_by: str = "canonical-dogfood") -> dict[str, Any]:
        """Generate/accept five Scene Expressions and compose an accepted Chapter."""
        root = Path(project_root)
        expression_store = ExpressionStore(root)
        accepted = []
        for index, scene_path in enumerate(sorted(root.glob("chapters/01/scenes/scene_01_*.yaml")), 1):
            prose = (root / "canonical_story" / "chapter_01" / f"scene_{index:02d}" / "expression.md").read_text(encoding="utf-8")
            candidate = expression_store.generate(scene_path, prose, executor={"kind": "canonical-reference"})
            accepted.append(expression_store.accept(candidate.candidate_id, accepted_by=accepted_by).model_dump(mode="json"))
        transitions = {
            "scene_01_02": {"transition_id": "transition_01_02", "before_scene": "scene_01_01", "after_scene": "scene_01_02", "revision": 1, "lifecycle": "accepted", "text": "The river wind carries Tomas's warning up the tower."}
        }
        composition = ChapterExpressionStore(root)
        composition.save_transitions("chapter_01", transitions)
        chapter = composition.compose("chapter_01", transitions=transitions, persist_transitions=True)
        accepted_chapter = composition.accept(chapter.artifact_id, accepted_by=accepted_by)
        return {"scene_expressions": accepted, "chapter_expression": accepted_chapter.model_dump(mode="json"), "transitions": transitions}

    def bootstrap_second_chapter(self, project_root: Path, *, accepted_by: str = "canonical-dogfood") -> dict[str, Any]:
        """Bootstrap the authored one-scene epilogue through native stores."""
        root = Path(project_root)
        artifact_store = ArtifactStore(root)
        outline = root / "chapters" / "02" / "outline.yaml"
        outline.parent.mkdir(parents=True, exist_ok=True)
        outline.write_text(yaml.safe_dump({"chapter_id": "chapter_02", "chapter_number": 2, "scenes": ["scene_02_01"]}, sort_keys=False), encoding="utf-8")
        outline_meta = artifact_store.accept(outline, "chapter_outline", accepted_by=accepted_by, rationale="canonical epilogue structure")
        source = root / "canonical_story" / "chapter_02" / "scene_01" / "realization.yaml"
        scene = root / "chapters" / "02" / "scenes" / "scene_02_01.yaml"
        scene.parent.mkdir(parents=True, exist_ok=True)
        data = yaml.safe_load(source.read_text(encoding="utf-8")) or {}
        data.update({"id": "scene_02_01", "chapter_id": "chapter_02", "order": 1})
        scene.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")
        realization = artifact_store.accept(scene, "scene_realization", accepted_by=accepted_by, rationale="canonical epilogue realization")
        expression_store = ExpressionStore(root)
        prose = (root / "canonical_story" / "chapter_02" / "scene_01" / "expression.md").read_text(encoding="utf-8")
        candidate = expression_store.generate(scene, prose, executor={"kind": "canonical-reference"})
        expression = expression_store.accept(candidate.candidate_id, accepted_by=accepted_by)
        composition = ChapterExpressionStore(root)
        chapter = composition.compose("chapter_02")
        accepted_chapter = composition.accept(chapter.artifact_id, accepted_by=accepted_by)
        return {"outline": outline_meta.model_dump(mode="json"), "realization": realization.model_dump(mode="json"), "expression": expression.model_dump(mode="json"), "chapter_expression": accepted_chapter.model_dump(mode="json")}

    def bootstrap_book(self, project_root: Path, chapter_expression_ids: list[str], *, accepted_by: str = "canonical-dogfood") -> dict[str, Any]:
        store = BookExpressionStore(project_root)
        derived = store.compose([item.split(":", 1)[0] for item in chapter_expression_ids], title="The Lantern at Low Water")
        accepted = store.accept(derived["book_expression_id"], accepted_by=accepted_by)
        return {"derived": derived, "accepted": accepted}

    @staticmethod
    def external_edit_path(project_root: Path) -> Path:
        return Path(project_root) / "canonical_story" / "external_edit.md"
