from __future__ import annotations

import json
from types import SimpleNamespace

from auteur.blueprint import (
    EmotionalTrajectory,
    Genre,
    TargetAudience,
    TargetExperience,
)
from auteur.llm import LLMResponse
from auteur.narrative_ontology.architecture_preferences import (
    CausalDistributionPreference,
    ComplexityPreference,
    EngineHierarchyPreference,
    NarrativeArchitecturePreferences,
)
from auteur.story_discovery_brief import (
    DiscoveryBrief,
    DiscoveryBriefStoryType,
    assess_intent_adequacy,
)
from auteur.story_discovery_causality import CausalProfileRecord, assess_causal_diversity
from auteur.story_discovery_craft import (
    CraftAnalysis,
    CraftImpactRecord,
    ExternalActionShift,
    ReaderExperienceShift,
    build_craft_impact_request,
)
from auteur.story_discovery_craft_surface import compact_craft_lines


class Dumpable(SimpleNamespace):
    def model_dump(self, mode="json"):
        return dict(self.__dict__)


def _profile(key: str, strategy: str, actions: list[str], climax: str) -> CausalProfileRecord:
    return CausalProfileRecord(
        evidence_key=key,
        primary_strategy=strategy,
        causal_owner="protagonist-led",
        external_action_pattern=actions,
        pressure_system=f"pressure generated by {strategy}",
        reversal_mechanics=[f"reversal through {strategy}"],
        climax_mechanic=climax,
        scene_families=[f"{action} scene" for action in actions],
        evidence_gaps=[],
    )


class _DiversityClient:
    def __init__(self, classification: str):
        self.classification = classification

    def complete(self, request):
        pairs = json.loads(request.user.split("CAUSAL PROFILE PAIRS\n", 1)[1])
        return LLMResponse(
            text=json.dumps(
                {
                    "assessments": [
                        {
                            "left_evidence_key": pair["left_evidence_key"],
                            "right_evidence_key": pair["right_evidence_key"],
                            "classification": self.classification,
                            "shared_causal_mechanics": ["same premise"],
                            "material_differences": (
                                ["different actions and climax"]
                                if self.classification == "distinct"
                                else []
                            ),
                            "scene_consequence": (
                                "Major scenes materially differ."
                                if self.classification == "distinct"
                                else "Major scenes remain substantially the same."
                            ),
                            "rationale": "controlled Phase F dogfood assessment",
                        }
                        for pair in pairs
                    ]
                }
            ),
            input_tokens=1,
            output_tokens=1,
        )


def _candidate(candidate_id: str, title: str, target: TargetExperience):
    identity = SimpleNamespace(
        title=title,
        core_answer=f"Controlled identity for {title}.",
        central_engine=Dumpable(
            want="resolve the external objective",
            resistance="opposition blocks the direct route",
            conflict="the chosen causal mechanism drives escalating conflict",
            stakes="failure makes the loss permanent",
            change="the protagonist changes through the chosen strategy",
        ),
        story_type=Dumpable(genre="other", target_audience="adult"),
        target_experience=target,
        not_this=[],
        open_questions=[],
        author_overrides=[],
        hard_constraints=[],
    )
    return SimpleNamespace(candidate_id=candidate_id, identity=identity)


def test_d1_intent_adequacy_distinguishes_exploration_from_rankable_intent():
    inadequate = DiscoveryBrief(
        premise="A retired astronaut hears mission-control chatter in her empty apartment."
    )
    assert assess_intent_adequacy(inadequate).adequate is False

    adequate = DiscoveryBrief(
        premise=inadequate.premise,
        story_type=DiscoveryBriefStoryType(
            genre=Genre.SCI_FI,
            target_audience=TargetAudience.ADULT,
        ),
        target_experience=TargetExperience(
            primary_emotional_promise="haunted recognition",
            secondary_palette=["wonder", "grief"],
            emotional_trajectory=EmotionalTrajectory(
                pattern="unease -> recognition -> bittersweet agency",
                start="unease",
                midpoint="recognition",
                ending="bittersweet agency",
            ),
        ),
    )
    assert assess_intent_adequacy(adequate).adequate is True


def test_d2_causal_false_choice_requires_materially_different_scene_engines():
    profiles = {
        "evidence": _profile(
            "aaaaaaaa111111111111",
            "retrieve and authenticate provenance evidence",
            ["retrieve", "authenticate", "connect", "disclose"],
            "prove the director's ownership claim cannot survive",
        ),
        "systems": _profile(
            "bbbbbbbb222222222222",
            "weaponize incompatible institutional procedures",
            ["schedule", "trigger", "constrain", "force choice"],
            "force the director to violate his own rules publicly",
        ),
        "social": _profile(
            "cccccccc333333333333",
            "stage truthful social pressure that provokes self-exposure",
            ["stage", "frame truthfully", "provoke", "expose"],
            "provoke public self-incrimination",
        ),
    }
    assert assess_causal_diversity(_DiversityClient("distinct"), profiles).status == "qualified"
    assert (
        assess_causal_diversity(_DiversityClient("near_duplicate"), profiles).status
        == "not_adjudicable_near_duplicate"
    )


def test_d3_maximalism_and_mixed_causation_remain_architecture_preferences():
    target = TargetExperience(primary_emotional_promise="claustrophobic dread")
    primary = _candidate("candidate_1", "The Missing Room", target)
    alternative = _candidate("candidate_2", "Measured Walls", target)
    primary_profile = _profile(
        "aaaaaaaa111111111111",
        "force family confrontation as rooms erase avoidance",
        ["recognize", "confront", "reckon"],
        "the family confronts the injury governing the house",
    )
    alternative_profile = _profile(
        "bbbbbbbb222222222222",
        "investigate and contain an inherited spatial mechanism",
        ["map", "investigate", "contain"],
        "the family chooses what must be contained or released",
    )
    declared = {
        "architecture_preferences": NarrativeArchitecturePreferences(
            complexity=ComplexityPreference.MAXIMALIST,
            causal_distribution=CausalDistributionPreference.MIXED,
            engine_hierarchy=EngineHierarchyPreference.PRIMARY_WITH_LAYERS,
        ).model_dump(mode="json", exclude_none=True),
        "target_experience": target.model_dump(mode="json"),
    }
    request = build_craft_impact_request(
        primary,
        alternative,
        primary_profile,
        alternative_profile,
        "A family inherits a house that becomes one room smaller every night.",
        declared_author_intent=declared,
    )
    assert '"complexity": "maximalist"' in request.user
    assert '"causal_distribution": "mixed"' in request.user
    assert '"engine_hierarchy": "primary_with_layers"' in request.user
    assert "Architecture preferences are authorial architecture constraints, not emotions." in request.system
    assert "primary_with_layers still requires one legible governing engine" in request.system


def test_d4_craft_surface_teaches_concrete_weight_shifts():
    target = TargetExperience(
        primary_emotional_promise="painful dramatic irony",
        secondary_palette=["dread", "hope"],
        emotional_trajectory=EmotionalTrajectory(
            pattern="suspicion -> dread -> bittersweet agency",
            start="suspicion",
            midpoint="dread",
            ending="bittersweet agency",
        ),
    )
    candidates = [
        _candidate("candidate_1", "What She Saves", target),
        _candidate("candidate_2", "His Quiet Repair", target),
    ]
    profiles = {
        "candidate_1": _profile(
            "aaaaaaaa111111111111",
            "repair consequences under permanently incomplete knowledge",
            ["repair", "organize", "protect", "choose"],
            "the protagonist's own decisions resolve the external crisis",
        ),
        "candidate_2": _profile(
            "bbbbbbbb222222222222",
            "secret atonement through hidden intervention",
            ["conceal", "intervene", "compensate", "sacrifice"],
            "the brother sacrifices without confessing",
        ),
    }
    impact = CraftImpactRecord(
        primary_candidate_id="candidate_1",
        compared_candidate_id="candidate_2",
        primary_evidence_key=profiles["candidate_1"].evidence_key,
        compared_evidence_key=profiles["candidate_2"].evidence_key,
        craft_layers_changed=[
            "causal_ownership",
            "external_action",
            "scene_families",
            "story_texture",
            "reader_experience",
            "theme",
        ],
        causal_ownership_shift="More consequential turns originate with the brother.",
        external_action_shift=ExternalActionShift(
            add_or_emphasize=["conceal", "intervene", "compensate", "sacrifice"],
            de_emphasize=["direct protagonist-led repair"],
        ),
        scene_family_shift=["parallel hidden intervention", "near-discovery"],
        pressure_texture_shift="More hidden-action dramatic irony.",
        reader_experience_shift=ReaderExperienceShift(
            primary_promise_effect="preserved_but_reweighted",
            secondary_palette_effect=["more pity", "more moral discomfort"],
            trajectory_effect="Dread rises as hidden interventions accumulate.",
        ),
        thematic_effect="Atonement without confession gains weight.",
        gain="Stronger hidden causal pressure and moral complexity.",
        give_up="Some causal ownership by the declared protagonist.",
        composability="compatible_as_secondary",
        composition_note="Keep protagonist decisions decisive.",
        primary_risk="The brother can become the effective protagonist.",
        evidence_gaps=[],
    )
    analysis = CraftAnalysis(
        status="complete",
        primary_candidate_id="candidate_1",
        impacts={"candidate_2": impact},
    )
    text = "\n".join(compact_craft_lines(analysis, profiles, candidates))
    assert "You would write more: conceal, intervene, compensate, sacrifice" in text
    assert "Give up / reweight: Some causal ownership by the declared protagonist." in text
    assert "Composability: compatible as secondary" in text
    assert "Risk: The brother can become the effective protagonist." in text


def test_d5_emotional_hierarchy_remains_legible_under_complex_causation():
    target = TargetExperience(
        primary_emotional_promise="bittersweet meaningful agency",
        secondary_palette=["wonder", "grief", "moral urgency"],
        emotional_trajectory=EmotionalTrajectory(
            pattern="wonder -> frustration -> recognition -> bittersweet agency",
            start="wonder",
            midpoint="recognition",
            ending="bittersweet agency",
        ),
    )
    candidates = [
        _candidate("candidate_1", "Fixed Point", target),
        _candidate("candidate_2", "Annotations", target),
    ]
    profiles = {
        "candidate_1": _profile(
            "aaaaaaaa111111111111",
            "witness fixed history and carry knowledge into present action",
            ["witness", "recover testimony", "persuade", "act"],
            "present-day action changes responsibility without changing history",
        ),
        "candidate_2": _profile(
            "bbbbbbbb222222222222",
            "convert recovered history into contested public memory",
            ["curate", "authenticate", "publish", "defend"],
            "public memory changes while historical events remain fixed",
        ),
    }
    impact = CraftImpactRecord(
        primary_candidate_id="candidate_1",
        compared_candidate_id="candidate_2",
        primary_evidence_key=profiles["candidate_1"].evidence_key,
        compared_evidence_key=profiles["candidate_2"].evidence_key,
        craft_layers_changed=["pressure_system", "scene_families", "reader_experience"],
        causal_ownership_shift="More causal weight moves toward institutions and public memory.",
        external_action_shift=ExternalActionShift(
            add_or_emphasize=["curate", "publish", "defend"],
            de_emphasize=["intimate testimony"],
        ),
        scene_family_shift=["archive dispute", "public memory conflict"],
        pressure_texture_shift="More institutional resistance and public contest.",
        reader_experience_shift=ReaderExperienceShift(
            primary_promise_effect="preserved_but_reweighted",
            secondary_palette_effect=["more moral urgency"],
            trajectory_effect="Recognition produces more public-facing obligation.",
        ),
        thematic_effect="Who controls historical meaning gains emphasis.",
        gain="Greater social scope.",
        give_up="Some intimate witness texture.",
        composability="compatible_as_secondary",
        composition_note="Keep witnessing as the governing engine.",
        primary_risk="Institutional conflict can displace the human time-travel experience.",
        evidence_gaps=[],
    )
    analysis = CraftAnalysis(
        status="complete",
        primary_candidate_id="candidate_1",
        impacts={"candidate_2": impact},
    )
    text = "\n".join(compact_craft_lines(analysis, profiles, candidates))
    assert "Governing reader promise: bittersweet meaningful agency" in text
    assert "Supporting emotional palette: wonder, grief, moral urgency" in text
    assert "Emotional trajectory: wonder -> frustration -> recognition -> bittersweet agency" in text
    assert "Primary reader-promise effect: preserved but reweighted" in text
