"""Tests for the immutable publishing pipeline (auteur publish)."""

from __future__ import annotations

import re
import zipfile
from pathlib import Path

import pytest
import yaml

from auteur.expression.book import BookExpressionStore
from auteur.publish import (
    ALL_FORMATS,
    PublishError,
    PublishingSnapshot,
    publish,
)


def _make_book(tmp_path: Path) -> Path:
    project = tmp_path / "project"
    project.mkdir(parents=True, exist_ok=True)
    from conftest import copy_bootstrap_template as _cbt
    _cbt(project)
    book = BookExpressionStore(project).compose(
        ["chapter_01", "chapter_02"], title="The Lantern at Low Water"
    )
    BookExpressionStore(project).accept(book["book_expression_id"])
    return project


# ---------------------------------------------------------------------------
# PublishingSnapshot unit tests
# ---------------------------------------------------------------------------


class TestPublishingSnapshot:
    def test_reads_accepted_book(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        assert snapshot.title == "The Lantern at Low Water"
        assert snapshot.author == "Unknown Author"
        assert snapshot._manifest["revision"] >= 1
        assert len(snapshot._parsed["chapters"]) == 2

    def test_raises_on_missing_accepted(self, tmp_path: Path) -> None:
        with pytest.raises(PublishError, match="No accepted Book Expression"):
            PublishingSnapshot(tmp_path)

    def test_raises_on_no_book_dir(self, tmp_path: Path) -> None:
        (tmp_path / "book").mkdir(parents=True)
        with pytest.raises(PublishError, match="No accepted Book Expression"):
            PublishingSnapshot(tmp_path)

    def test_snapshot_identity_fallback(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        identity = project / "story_identity.yaml"
        identity.unlink()
        snapshot = PublishingSnapshot(project)
        assert snapshot.title == "The Lantern at Low Water"
        assert snapshot.author == "Unknown Author"

    def test_chapter_parsing(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        chapters = snapshot._parsed["chapters"]
        assert len(chapters) == 2
        assert chapters[0]["id"] == "chapter_01"
        assert chapters[1]["id"] == "chapter_02"
        assert all(ch["body"] for ch in chapters)


# ---------------------------------------------------------------------------
# HTML rendering
# ---------------------------------------------------------------------------


class TestHtmlRendering:
    def test_render_html(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        output = tmp_path / "book.html"
        result = snapshot.render_html(output)
        assert result["format"] == "html"
        assert result["output_hash"].startswith("sha256:")
        assert output.exists()
        html = output.read_text(encoding="utf-8")
        assert "<!DOCTYPE html>" in html
        assert "The Lantern at Low Water" in html
        assert "Generated by Auteur" in html
        assert "<nav" in html

    def test_html_title_page(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        html = snapshot.render_html(tmp_path / "with_title.html")
        content = (tmp_path / "with_title.html").read_text(encoding="utf-8")
        assert '<div class="title-page">' in content
        assert "Generated by Auteur" in content

    def test_html_no_title_page(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        snapshot.render_html(tmp_path / "no_title.html", title_page=False)
        content = (tmp_path / "no_title.html").read_text(encoding="utf-8")
        assert '<div class="title-page">' not in content

    def test_html_no_toc(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        snapshot.render_html(tmp_path / "no_toc.html", toc=False)
        content = (tmp_path / "no_toc.html").read_text(encoding="utf-8")
        assert '<nav id="toc"' not in content

    def test_html_with_custom_css(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        custom = "body { background: yellow; }"
        snapshot.render_html(tmp_path / "custom.html", css=custom)
        content = (tmp_path / "custom.html").read_text(encoding="utf-8")
        assert "background: yellow" in content

    def test_html_chapter_content(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        snapshot.render_html(tmp_path / "content.html")
        content = (tmp_path / "content.html").read_text(encoding="utf-8")
        assert '<div class="chapter"' in content
        assert "Chapter 1" in content
        assert "Chapter 2" in content

    def test_html_no_markers(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        snapshot.render_html(tmp_path / "clean.html")
        content = (tmp_path / "clean.html").read_text(encoding="utf-8")
        assert "<!-- auteur:" not in content

    def test_html_raises_on_existing(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        output = tmp_path / "exists.html"
        output.write_text("existing", encoding="utf-8")
        with pytest.raises(FileExistsError):
            snapshot.render_html(output)


# ---------------------------------------------------------------------------
# EPUB rendering
# ---------------------------------------------------------------------------


class TestEpubRendering:
    def test_render_epub(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        output = tmp_path / "book.epub"
        result = snapshot.render_epub(output)
        assert result["format"] == "epub"
        assert result["output_hash"].startswith("sha256:")
        assert output.exists()
        assert output.stat().st_size > 200

    def test_epub_is_valid_zip(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        output = tmp_path / "valid.epub"
        snapshot.render_epub(output)
        with zipfile.ZipFile(output, "r") as zf:
            names = zf.namelist()
        assert "mimetype" in names
        assert "META-INF/container.xml" in names
        assert "OEBPS/content.opf" in names
        assert "OEBPS/nav.xhtml" in names
        assert "OEBPS/stylesheet.css" in names
        assert any(n.startswith("OEBPS/chapter_") and n.endswith(".xhtml") for n in names)

    def test_epub_chapter_count(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        output = tmp_path / "count.epub"
        snapshot.render_epub(output)
        with zipfile.ZipFile(output, "r") as zf:
            names = zf.namelist()
        chapters = [n for n in names if n.startswith("OEBPS/chapter_") and n.endswith(".xhtml")]
        assert len(chapters) == 2

    def test_epub_content_has_title(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        output = tmp_path / "title.epub"
        snapshot.render_epub(output)
        with zipfile.ZipFile(output, "r") as zf:
            opf = zf.read("OEBPS/content.opf").decode("utf-8")
        assert "The Lantern at Low Water" in opf
        assert "Unknown Author" in opf

    def test_epub_no_markers(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        output = tmp_path / "clean.epub"
        snapshot.render_epub(output)
        with zipfile.ZipFile(output, "r") as zf:
            for name in zf.namelist():
                if name.endswith(".xhtml"):
                    data = zf.read(name).decode("utf-8")
                    assert "<!-- auteur:" not in data

    def test_epub_raises_on_existing(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        output = tmp_path / "exists.epub"
        output.write_bytes(b"existing")
        with pytest.raises(FileExistsError):
            snapshot.render_epub(output)


# ---------------------------------------------------------------------------
# Snapshot manifest
# ---------------------------------------------------------------------------


class TestSnapshotManifest:
    def test_run_record_returned(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        r1 = snapshot.render_html(tmp_path / "book.html")
        r2 = snapshot.render_epub(tmp_path / "book.epub")
        run = snapshot.save_snapshot([r1, r2])
        assert run["run_type"] == "publishing_run"
        assert run["snapshot_id"].startswith("pub_")
        assert run["title"] == "The Lantern at Low Water"
        assert run["author"] == "Unknown Author"
        assert run["source_book"]["revision"] >= 1
        assert run["source_book"]["content_hash"].startswith("sha256:")
        assert run["formats"] == ["html", "epub"]
        assert len(run["renderers"]) == 2
        assert run["renderers"][0]["format"] == "html"
        assert run["renderers"][1]["format"] == "epub"
        assert "created_at" in run

    def test_immutable_snapshot_written_once(self, tmp_path: Path) -> None:
        """The snapshot file (no renderers) is written once and never overwritten."""
        project = _make_book(tmp_path)
        snap_dir = project / ".auteur" / "publishing"

        # First publish
        snapshot = PublishingSnapshot(project)
        r1 = snapshot.render_html(tmp_path / "book.html")
        snapshot.save_snapshot([r1])
        imm_snap = yaml.safe_load(
            (snap_dir / f"{snapshot._snapshot_id}.yaml").read_text(encoding="utf-8")
        )
        assert imm_snap["snapshot_id"] == snapshot._snapshot_id
        assert "renderers" not in imm_snap
        assert imm_snap["artifact_type"] == "book_publishing_snapshot"

        # Second publish from same source — snapshot file must be unchanged
        snapshot2 = PublishingSnapshot(project)
        assert snapshot2._snapshot_id == snapshot._snapshot_id
        r2 = snapshot2.render_html(tmp_path / "book_v2.html")
        snapshot2.save_snapshot([r2])
        imm_snap2 = yaml.safe_load(
            (snap_dir / f"{snapshot._snapshot_id}.yaml").read_text(encoding="utf-8")
        )
        assert imm_snap2 == imm_snap  # byte-identical, never overwritten

    def test_latest_is_convenience_pointer(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        snapshot = PublishingSnapshot(project)
        r1 = snapshot.render_html(tmp_path / "first.html")
        snapshot.save_snapshot([r1])
        latest = yaml.safe_load(
            (project / ".auteur" / "publishing" / "latest.yaml").read_text(encoding="utf-8")
        )
        assert latest["run_type"] == "publishing_run"
        assert latest["snapshot_id"] == snapshot._snapshot_id
        assert len(latest["renderers"]) == 1

    def test_run_history_recorded(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        publish(project, formats=["html"], html_output=tmp_path / "a.html")
        publish(project, formats=["epub"], epub_output=tmp_path / "a.epub")
        runs_dir = project / ".auteur" / "publishing" / "runs"
        run_files = sorted(runs_dir.glob("run_*.yaml"))
        assert len(run_files) == 2
        run0 = yaml.safe_load(run_files[0].read_text(encoding="utf-8"))
        run1 = yaml.safe_load(run_files[1].read_text(encoding="utf-8"))
        assert run0["run_type"] == "publishing_run"
        assert run0["formats"] == ["html"]
        assert run1["formats"] == ["epub"]


# ---------------------------------------------------------------------------
# publish() convenience function
# ---------------------------------------------------------------------------


class TestPublishFunction:
    def test_publish_html(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        out = tmp_path / "pub.html"
        result = publish(project, formats=["html"], html_output=out)
        assert result["snapshot_id"].startswith("pub_")
        assert result["title"] == "The Lantern at Low Water"
        assert out.exists()

    def test_publish_epub(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        out = tmp_path / "pub.epub"
        result = publish(project, formats=["epub"], epub_output=out)
        assert result["snapshot_id"].startswith("pub_")
        assert out.exists()

    def test_publish_both_formats(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        out_dir = tmp_path / "output"
        out_dir.mkdir()
        result = publish(project, formats=["html", "epub"], output_dir=out_dir)
        assert len(result["renderers"]) == 2
        assert (out_dir / "book.html").exists()
        assert (out_dir / "book.epub").exists()

    def test_publish_saves_snapshot(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        publish(project, formats=["html"], html_output=tmp_path / "book.html")
        assert (project / ".auteur" / "publishing" / "latest.yaml").exists()

    def test_publish_error_on_bad_format(self, tmp_path: Path) -> None:
        project = _make_book(tmp_path)
        with pytest.raises(PublishError, match="unknown format"):
            publish(project, formats=["pdf"])


# ---------------------------------------------------------------------------
# End-to-end: output contains no Auteur machinery
# ---------------------------------------------------------------------------


def test_output_no_auteur_markers(tmp_path: Path) -> None:
    project = _make_book(tmp_path)
    out = tmp_path / "e2e.html"
    publish(project, formats=["html"], html_output=out)
    content = out.read_text(encoding="utf-8")
    assert "<!-- auteur:" not in content
    assert "<!--" not in content or "Auteur" not in content


def test_all_formats_constant_consistent(tmp_path: Path) -> None:
    assert "html" in ALL_FORMATS
    assert "epub" in ALL_FORMATS
    assert len(ALL_FORMATS) == 2
